# Generated by Django 2.2.5 on 2021-11-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Simulation',
            fields=[
                ('id', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mass_ratio', models.CharField(max_length=10)),
                ('impact_parameter', models.CharField(max_length=10)),
                ('proj_axis', models.CharField(max_length=1)),
            ],
        ),
    ]
