# Generated by Django 2.2.5 on 2021-11-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clummp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='centroid_distances',
            field=models.FloatField(default=-1.0),
        ),
    ]
