# Generated by Django 2.2.5 on 2021-11-05 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clummp', '0002_simulation_centroid_distances'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulation',
            old_name='centroid_distances',
            new_name='centroid_distance',
        ),
    ]
