# Generated by Django 2.2.5 on 2021-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clummp', '0003_auto_20211105_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='filename',
            field=models.CharField(default='', max_length=120),
        ),
    ]
