# Generated by Django 2.2.5 on 2021-11-30 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clummp', '0004_simulation_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='container_id',
            field=models.CharField(default='', max_length=120),
        ),
    ]
